### ISSUE TITLE
Student ticket button/form submission does not change state when submitted

### ISSUE THREAD

**Issue by ProfessorTom** [DevSpaceHuntsville/WebsiteAndApi#8]
**Steps for Reproduction**
1. Enter text in the email text box on the Tickets page.
2. Press enter or click the "Get Student Access Code" button.

**Expected Behavior**
There should be some kind of animation (i.e. spinning circular wait .gif) or state change (button changes color slightly when depressed) or progress indicator once the email address is submitted.

**Actual Behavior**
No state change though the website does process the requests. In fact the page will submit multiple requests. (If, for example, the user clicks the button more than once or presses return more than once.)

**Comment by freestylecoder** [comment]
You are correct that we don't do anything while the process is pending. It does display a message (either success or error) on completion.

**Comment by freestylecoder** [comment]
Did this and issue #9 get fixed with your pull request?

**Comment by ProfessorTom** [comment]
Yes, it did.

On Saturday, June 25, 2016, Chris Gardner <notifications@github.com> wrote:

> Did this and issue #9
> <https://github.com/DevSpaceHuntsville/WebsiteAndApi/issues/9> get fixed
> with your pull request?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DevSpaceHuntsville/WebsiteAndApi/issues/8#issuecomment-228540724>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADCK8BY19M0ef8H5MX2uXWa3EYLQYPTbks5qPSsvgaJpZM4IafNP>
> .
>


-- 
A programmer is a tool which converts caffeine to source code

**Comment by freestylecoder** [comment]
Cool.  I'm going to close the issues.  Thank you, sir.
