### ISSUE TITLE
Student ticket button/form allows multiple submissions

### ISSUE THREAD

**Issue by ProfessorTom** [DevSpaceHuntsville/WebsiteAndApi#9]
Steps for Reproduction
1. Enter text in the email text box on the Tickets page.
2. Press enter or click the "Get Student Access Code" button multiple times before the first request has finished processing.

Expected Behavior
Once submitted, form submission should be disabled until the previous request has completed or timed out.

Actual Behavior
The page will more than happily submit multiple requests without waiting for previous requests to complete or time out.

**Comment by freestylecoder** [comment]
The server _should_ handle this and only process the request once. Might want to check to make sure. Since the email address is a unique key in the database, there isn't really a way they could generate more than one; the subsequent inserts would fail.

Fixing issue #8 should fix this.

**Comment by freestylecoder** [comment]
See comments in #8
